### ISSUE TITLE
Serveurs actuels

### ISSUE THREAD

**Issue by Gorbus** [cquest/dvf_as_api#2]
Bonjour,

Serait-il possible de savoir sur quel type d'architecture l'API est-elle hébergée en ce moment ? (aws, dédié ovh, autre ?)

Les résultats étant rapide j'aurais aimé utiliser une architecture identique.

Merci par avance.

**Comment by cquest** [comment]
L'API tourne dans un container LXC sur un serveur dédié utilisant proxmox et situé... dans mon "datacenter" perso

https://www.computel.fr/2019/07/07/la-quincaillerie/

Sont alloués à ce container:
- 2Go de RAM
- 4 coeurs (CPU Xéon X5670)

Le stockage est fait sur un pool ZFS de 6 disques en RAIDZ2 + cache sur SSD.
