### ISSUE TITLE
Probleme CREATION INDEX avec SPGIST et data type geometry

### ISSUE THREAD

**Issue by Gorbus** [cquest/dvf_as_api#3]
Bonjour,

Lors de l'import j'ai l'erreur suivante :

> ERROR: data type geometry has no default operator class for access method "spgist"
> HINT: You must specify an operator class for the index or define a default operator class for the data type

Cette erreur est liée à la ligne suivante du script : 
`CREATE INDEX ON dvf_parcelles USING spgist (geom);`

J'ai pu contourner l'erreur en remplaçant SPGIST par GIST dans la ligne de code mais je pense que les performances en pâtissent. Pourriez vous m'aider sur le sujet ?

**Comment by cldt-fr** [comment]
Bonjour,

Essayer de mettre à jour Postgres en version 10 ou 11, les indexage BRIN et SPGIST sont disponible à partir de la version 9.5.

**Comment by johanovic** [comment]
L'erreur a aussi lieu en Postgres version 10. Pourtant spgist fait partie de version 10: https://www.postgresql.org/docs/10/spgist.html

**Comment by cquest** [comment]
Vous pouvez remplacer SPGIST par GIST.
